version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "employee"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1k98k71y0mgmp"
s3_prefix = "employee"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
