AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  employee-api

  Sample SAM Template for employee-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  EmployeeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: EmployeeQueue

  HandlerLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: employee/employee_api/src/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !Ref EmployeeQueue
      Events:
        APIGateway:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /employee
            Method: post

  SQSQueueProcessorLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: employee_process/employee_process_api/src/
      Handler: processor.processor_lambda
      Runtime: python3.7
      Policies:
        - SQSPollerPolicy:
            QueueName:
              !Ref EmployeeQueue
        - DynamoDBCrudPolicy:
            TableName:
              !Ref EmployeeTable
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt EmployeeQueue.Arn
            BatchSize: 10

  EmployeeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: employees
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: Designation
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: "HASH"
        - AttributeName: Designation
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EmployeeApi:
    Description: "API Gateway endpoint URL for Prod stage for Employee function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  HandlerLambda:
    Description: "Employee handler Lambda Function ARN"
    Value: !GetAtt HandlerLambda.Arn
  HandlerLambdaIamRole:
    Description: "Implicit IAM Role created for employee function"
    Value: !GetAtt HandlerLambdaRole.Arn
